/**
 * Hairstyle Database — HairMatch (B3-01)
 *
 * 25 curated hairstyles mapped to face shapes, hair types,
 * occasions, and gender presentations.
 */

import type { StyleEntry } from './recommender.types';

export const STYLES_DB: StyleEntry[] = [
  // =========================================================================
  // OVAL — most versatile, suits almost everything
  // =========================================================================
  {
    id: 'classic-layers',
    name: 'Classic Layers',
    description: 'Flowing layers that frame the face and add movement.',
    primaryShapes: ['oval'],
    secondaryShapes: ['heart', 'oblong'],
    suitableHairTypes: ['straight', 'wavy'],
    suitableOccasions: ['everyday', 'professional'],
    genderPresentations: ['feminine', 'androgynous'],
    imagePath: '/assets/styles/classic-layers.jpg',
    tags: ['medium', 'layers', 'versatile'],
  },
  {
    id: 'textured-crop',
    name: 'Textured Crop',
    description: 'A short, textured style with natural movement on top.',
    primaryShapes: ['oval'],
    secondaryShapes: ['square', 'oblong'],
    suitableHairTypes: ['straight', 'wavy', 'curly'],
    suitableOccasions: ['everyday', 'professional'],
    genderPresentations: ['masculine', 'androgynous'],
    imagePath: '/assets/styles/textured-crop.jpg',
    tags: ['short', 'textured', 'low-maintenance'],
  },
  {
    id: 'curtain-bangs',
    name: 'Curtain Bangs',
    description: 'Soft center-parted bangs that flatter balanced proportions.',
    primaryShapes: ['oval'],
    secondaryShapes: ['round', 'heart'],
    suitableHairTypes: ['straight', 'wavy'],
    suitableOccasions: ['everyday', 'formal'],
    genderPresentations: ['feminine', 'androgynous'],
    imagePath: '/assets/styles/curtain-bangs.jpg',
    tags: ['bangs', 'medium', 'trendy'],
  },

  // =========================================================================
  // ROUND — styles that add length and angles
  // =========================================================================
  {
    id: 'long-layers-side-part',
    name: 'Long Layers with Side Part',
    description: 'Long layers swept to one side to create vertical lines and elongate the face.',
    primaryShapes: ['round'],
    secondaryShapes: ['square', 'oval'],
    suitableHairTypes: ['straight', 'wavy'],
    suitableOccasions: ['everyday', 'professional', 'formal'],
    genderPresentations: ['feminine'],
    imagePath: '/assets/styles/long-layers-side-part.jpg',
    tags: ['long', 'layers', 'side-part'],
  },
  {
    id: 'pixie-with-height',
    name: 'Pixie with Volume',
    description: 'A short pixie cut styled with height on top to elongate the face.',
    primaryShapes: ['round'],
    secondaryShapes: ['oval'],
    suitableHairTypes: ['straight', 'wavy'],
    suitableOccasions: ['everyday', 'professional'],
    genderPresentations: ['feminine', 'androgynous'],
    imagePath: '/assets/styles/pixie-with-height.jpg',
    tags: ['short', 'pixie', 'volume'],
  },
  {
    id: 'lob-asymmetric',
    name: 'Asymmetric Lob',
    description: 'A long bob cut slightly shorter on one side for asymmetric angles.',
    primaryShapes: ['round'],
    secondaryShapes: ['square', 'oval'],
    suitableHairTypes: ['straight', 'wavy', 'curly'],
    suitableOccasions: ['everyday', 'professional'],
    genderPresentations: ['feminine', 'androgynous'],
    imagePath: '/assets/styles/lob-asymmetric.jpg',
    tags: ['medium', 'bob', 'asymmetric'],
  },
  {
    id: 'undercut-fade',
    name: 'Undercut Fade',
    description: 'Faded sides with volume on top creating a strong vertical line.',
    primaryShapes: ['round'],
    secondaryShapes: ['square', 'oval'],
    suitableHairTypes: ['straight', 'wavy', 'curly'],
    suitableOccasions: ['everyday', 'professional'],
    genderPresentations: ['masculine'],
    imagePath: '/assets/styles/undercut-fade.jpg',
    tags: ['short', 'fade', 'undercut', 'masculine'],
  },

  // =========================================================================
  // SQUARE — styles that soften strong jawlines
  // =========================================================================
  {
    id: 'soft-waves',
    name: 'Soft Waves',
    description: 'Loose, romantic waves that soften the angles of a square jaw.',
    primaryShapes: ['square'],
    secondaryShapes: ['oblong', 'oval'],
    suitableHairTypes: ['wavy', 'curly'],
    suitableOccasions: ['everyday', 'formal'],
    genderPresentations: ['feminine', 'androgynous'],
    imagePath: '/assets/styles/soft-waves.jpg',
    tags: ['long', 'waves', 'romantic'],
  },
  {
    id: 'side-swept-fringe',
    name: 'Side-Swept Fringe',
    description: 'A diagonal fringe that breaks the width of the forehead and softens the jaw.',
    primaryShapes: ['square'],
    secondaryShapes: ['round', 'oval'],
    suitableHairTypes: ['straight', 'wavy'],
    suitableOccasions: ['everyday', 'professional'],
    genderPresentations: ['feminine', 'androgynous'],
    imagePath: '/assets/styles/side-swept-fringe.jpg',
    tags: ['medium', 'fringe', 'bangs'],
  },
  {
    id: 'textured-quiff',
    name: 'Textured Quiff',
    description: 'Volume swept upward and back to draw attention away from a wide jaw.',
    primaryShapes: ['square'],
    secondaryShapes: ['round', 'oval'],
    suitableHairTypes: ['straight', 'wavy'],
    suitableOccasions: ['everyday', 'professional'],
    genderPresentations: ['masculine'],
    imagePath: '/assets/styles/textured-quiff.jpg',
    tags: ['short', 'quiff', 'volume', 'masculine'],
  },
  {
    id: 'curly-shag',
    name: 'Curly Shag',
    description: 'Layered shag haircut that adds softness around a strong jawline.',
    primaryShapes: ['square'],
    secondaryShapes: ['oblong', 'oval'],
    suitableHairTypes: ['curly', 'coily'],
    suitableOccasions: ['everyday'],
    genderPresentations: ['feminine', 'androgynous'],
    imagePath: '/assets/styles/curly-shag.jpg',
    tags: ['medium', 'curly', 'shag', 'layers'],
  },

  // =========================================================================
  // HEART — styles that balance a wider forehead and narrow jaw
  // =========================================================================
  {
    id: 'chin-length-bob',
    name: 'Chin-Length Bob',
    description: 'A classic bob ending at the chin to add width at the jaw level.',
    primaryShapes: ['heart'],
    secondaryShapes: ['oval', 'round'],
    suitableHairTypes: ['straight', 'wavy'],
    suitableOccasions: ['professional', 'everyday'],
    genderPresentations: ['feminine', 'androgynous'],
    imagePath: '/assets/styles/chin-length-bob.jpg',
    tags: ['short', 'bob', 'classic'],
  },
  {
    id: 'side-part-waves',
    name: 'Side Part Waves',
    description: 'Deep side-parted waves that balance a wider forehead.',
    primaryShapes: ['heart'],
    secondaryShapes: ['oval', 'round'],
    suitableHairTypes: ['wavy', 'curly'],
    suitableOccasions: ['everyday', 'formal'],
    genderPresentations: ['feminine'],
    imagePath: '/assets/styles/side-part-waves.jpg',
    tags: ['long', 'waves', 'side-part'],
  },
  {
    id: 'medium-shag',
    name: 'Medium Shag',
    description: 'Layered medium shag that adds width through the mid-lengths to balance the jaw.',
    primaryShapes: ['heart'],
    secondaryShapes: ['square', 'oval'],
    suitableHairTypes: ['wavy', 'curly', 'coily'],
    suitableOccasions: ['everyday'],
    genderPresentations: ['feminine', 'androgynous'],
    imagePath: '/assets/styles/medium-shag.jpg',
    tags: ['medium', 'shag', 'layers', 'boho'],
  },
  {
    id: 'pompadour',
    name: 'Pompadour',
    description: 'Classic pompadour sweeping volume back to minimize a wide forehead.',
    primaryShapes: ['heart'],
    secondaryShapes: ['oval', 'round'],
    suitableHairTypes: ['straight', 'wavy'],
    suitableOccasions: ['everyday', 'professional'],
    genderPresentations: ['masculine'],
    imagePath: '/assets/styles/pompadour.jpg',
    tags: ['short', 'pompadour', 'classic', 'masculine'],
  },

  // =========================================================================
  // OBLONG — styles that add width and reduce apparent length
  // =========================================================================
  {
    id: 'blunt-bob',
    name: 'Blunt Bob',
    description: 'A bold, blunt-cut bob that adds width and breaks a long face profile.',
    primaryShapes: ['oblong'],
    secondaryShapes: ['square', 'oval'],
    suitableHairTypes: ['straight', 'wavy'],
    suitableOccasions: ['professional', 'everyday'],
    genderPresentations: ['feminine', 'androgynous'],
    imagePath: '/assets/styles/blunt-bob.jpg',
    tags: ['short', 'bob', 'blunt'],
  },
  {
    id: 'fringe-bangs',
    name: 'Full Fringe Bangs',
    description: 'Straight-across full bangs that visually shorten a long face.',
    primaryShapes: ['oblong'],
    secondaryShapes: ['square', 'oval'],
    suitableHairTypes: ['straight', 'wavy'],
    suitableOccasions: ['everyday'],
    genderPresentations: ['feminine', 'androgynous'],
    imagePath: '/assets/styles/fringe-bangs.jpg',
    tags: ['medium', 'bangs', 'fringe'],
  },
  {
    id: 'voluminous-curls',
    name: 'Voluminous Curls',
    description: 'Wide, bouncy curls that add horizontal volume to balance a long face.',
    primaryShapes: ['oblong'],
    secondaryShapes: ['heart', 'round'],
    suitableHairTypes: ['curly', 'coily'],
    suitableOccasions: ['everyday', 'formal'],
    genderPresentations: ['feminine', 'androgynous'],
    imagePath: '/assets/styles/voluminous-curls.jpg',
    tags: ['long', 'curly', 'volume'],
  },
  {
    id: 'crew-cut',
    name: 'Crew Cut',
    description: 'Short on the sides with a defined top that adds width without length.',
    primaryShapes: ['oblong'],
    secondaryShapes: ['oval', 'square'],
    suitableHairTypes: ['straight', 'wavy'],
    suitableOccasions: ['everyday', 'professional'],
    genderPresentations: ['masculine'],
    imagePath: '/assets/styles/crew-cut.jpg',
    tags: ['short', 'crew', 'classic', 'masculine'],
  },

  // =========================================================================
  // UNIVERSAL — works across multiple shapes
  // =========================================================================
  {
    id: 'natural-afro',
    name: 'Natural Afro',
    description: 'A full natural afro that adds beautiful volume in all directions.',
    primaryShapes: ['oblong', 'heart'],
    secondaryShapes: ['oval', 'square', 'round'],
    suitableHairTypes: ['coily'],
    suitableOccasions: ['everyday', 'professional', 'formal'],
    genderPresentations: ['feminine', 'masculine', 'androgynous'],
    imagePath: '/assets/styles/natural-afro.jpg',
    tags: ['natural', 'afro', 'coily', 'universal'],
  },
  {
    id: 'loose-updo',
    name: 'Loose Updo',
    description: 'A relaxed updo with face-framing pieces for any occasion.',
    primaryShapes: ['oval', 'round'],
    secondaryShapes: ['heart', 'oblong', 'square'],
    suitableHairTypes: ['straight', 'wavy', 'curly'],
    suitableOccasions: ['formal', 'everyday'],
    genderPresentations: ['feminine', 'androgynous'],
    imagePath: '/assets/styles/loose-updo.jpg',
    tags: ['updo', 'long', 'formal', 'elegant'],
  },
  {
    id: 'wolf-cut',
    name: 'Wolf Cut',
    description: 'Shaggy layers blended from crown to ends — a modern classic for all shapes.',
    primaryShapes: ['oval', 'square'],
    secondaryShapes: ['heart', 'round', 'oblong'],
    suitableHairTypes: ['wavy', 'curly', 'straight'],
    suitableOccasions: ['everyday'],
    genderPresentations: ['feminine', 'androgynous', 'masculine'],
    imagePath: '/assets/styles/wolf-cut.jpg',
    tags: ['medium', 'wolf', 'shag', 'trendy', 'universal'],
  },
  {
    id: 'buzz-cut',
    name: 'Buzz Cut',
    description: 'Uniform very short cut — clean, bold, and works with all shapes.',
    primaryShapes: ['oval', 'round', 'square'],
    secondaryShapes: ['heart', 'oblong'],
    suitableHairTypes: ['straight', 'wavy', 'curly', 'coily'],
    suitableOccasions: ['everyday', 'professional'],
    genderPresentations: ['masculine', 'androgynous'],
    imagePath: '/assets/styles/buzz-cut.jpg',
    tags: ['short', 'buzz', 'minimal', 'masculine'],
  },
  {
    id: 'braided-crown',
    name: 'Braided Crown',
    description: 'A braided updo that frames any face shape with elegance.',
    primaryShapes: ['oval', 'heart'],
    secondaryShapes: ['square', 'round', 'oblong'],
    suitableHairTypes: ['straight', 'wavy', 'curly', 'coily'],
    suitableOccasions: ['formal', 'everyday'],
    genderPresentations: ['feminine'],
    imagePath: '/assets/styles/braided-crown.jpg',
    tags: ['braid', 'updo', 'formal', 'elegant'],
  },
];
